# ===== UWSM Check =====
exec-once = ~/.local/share/dotfiles/bin/check-uwsm

# ===== Theme/cursor settings =====
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Essential GUI Fallbacks =====
# Ensures critical apps load even if the systemd graphical session acts up
exec-once = hyprpaper
exec-once = walker --gapplication-service
exec-once = elephant
exec-once = mako
